# Title and tag line
title: '이가은의 포트폴리오'

description: "이가은 (Lee Ga-eun)<br>Backend Developer<br>AI Engineer"

# Images
avatar: 'IMG_1282.JPG'
background: 'stacked-peaks-haikei.png'
favicon: 'favicon.ico'

# Online profiles
github-user: 'Leegaeune' 
blog_url: 'https://blog.naver.com/ga_ag_' 
email: 'igaeun916@gmail.com' 
