# Title and tag line
title: '이가은의 포트폴리오'

description: "이가은 (Lee Ga-eun)"

# Images
avatar: 'IMG_1282.JPG'
background: 'stacked-peaks-haikei.png'
favicon: 'favicon.ico'

# Online profiles
github-user: 'Leegaeune' 
blog_url: 'https://leegaeune.github.io/goag_blog/' 
email: 'igaeun916@gmail.com' 
