# Title and tag line
title: '이가은의 포트폴리오'
description: '이가은 (Lee Ga-eun) Backend Developer AI Engineer'

# Images
avatar: 'IMG_1282.JPG'
background: 'stacked-peaks-haikei.png' # 오타 수정
favicon: 'favicon.ico'

# 아래 내용은 수정할 필요 없습니다.
# Online profiles
facebook: 'myfacebook'
twitter: 'mytwitter'
youtube: 'myyoutube'
github-user: 'mygithub'
tumblr: 'mytumblr'
weibo: 'myweibo'
vk: 'myvk'
blog_url: 'myblog.blog.com'
email: 'hello@example.com'
messenger: 'myfbchat'
